[project]
name = "fiberoripy"
version = "1.0.13"
description = "Fiber orientation models and closures"
authors = [{name="Nils Meyer", email = "nils.meyer@kit.edu"}]
license = {file = "LICENSE"}
readme = "README.md"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.black]
line-length = 79
